name: LHCI-lighthouse-plugin
on: push
jobs:
  lighthouse-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn add --no-lockfile lighthouse-plugin-field-performance
      - name: Audit URLs with Field Performance Plugin
        uses: ./
        with:
          urls: |
            https://supermario.deco.site/
          configPath: '.github/lighthouse/lighthouserc-plugin.js'
          temporaryPublicStorage: true