# name: Lighthouse CI
# on: push
# jobs:
#   lighthouse:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         # os: [ ubuntu-latest, macos-12, windows-2022 ]
#         os: [ubuntu-latest]
#     steps:
#       - uses: actions/checkout@v3
#       - uses: denoland/setup-deno@v1.1.1
#         with:
#           deno-version: v1.x # Run with latest stable Deno.
#       - run: 'deno task lint'    
#       - name: Audit URLs using Lighthouse
#         uses: treosh/lighthouse-ci-action@v9
#         with:
#           urls: |
#             https://deco-sites-supermario--dev.deno.dev/
#           budgetPath: .github/lighthouse/budget.json # test performance budgets
#           configPath: '.github/lighthouse/lighthouserc-assertions.json'
#           uploadArtifacts: true # save results as an action artifacts
#           temporaryPublicStorage: true # upload lighthouse report to the temporary storage